### ISSUE TITLE
Can't set 'toggles' attribute false in HTML 

### ISSUE THREAD

**Issue by ghost** [PolymerElements/paper-radio-button#28]
I am trying to set up a paper-radio-group and want a single selection to always exist. In other words I don't want to be able to toggle the selected option off. I see that there is a 'toggles' attribute that should accomplish this. It is set to true by default, which from what I've read about HTML boolean attributes this is a problem since it would be true if present as an attribute and false otherwise. Here is my code:

``` html
<paper-radio-group selected="{{item.type}}">
  <paper-radio-button toggles="false" name="info">
    Info
  </paper-radio-button>
  <paper-radio-button toggles="false" name="link">
    Link
  </paper-radio-button>
</paper-radio-group>
```

I've tried `toggles?="false"` and omitting the attribute but I get the same result. If I tap on the same button repeatedly it toggles.

**Comment by notwaldorf** [comment]
I am fixing this in https://github.com/PolymerElements/paper-radio-group/pull/9. `toggles` is a bit of a misnamed attribute, and super confusing in this case-- it actually means whether the button can stay "active" after being pressed (unlike, say, a normal button, which has `toggles=false`).

The problem is in the `paper-radio-group`, which should not allow de-selecting the active selected item.

**Comment by ghost** [comment]
Great! I'll look forward to the changes.

**Comment by zishanj** [comment]
I am also facing this issue... @notwaldorf Is there any update on it's fix? I have tried the latest master but the issue is still there.
